name: "Daily Build"

on:
  workflow_dispatch:
 
env:
  BUILD_TYPE: Release

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: mkdir ${{github.workspace}}/build

# "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86

    - name: Configure CMake
      run: |
        $env:PATH="C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/" + $env:PATH
        cmake -G "NMake Makefiles" -DTARGET_PROCESSOR=x86 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build wxUiEditor
      run: |
        $env:PATH="C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/" + $env:PATH
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target wxUiEditor

    - name: Create Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WindowsExecutable
        path: |
          build/bin/Release/wxUiEditor.exe

  buildUnix:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: mkdir ${{github.workspace}}/build

    - name: Install other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libgtk-3-dev

    - name: Install GCC 11.4
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install gcc-11 g++-11 -y
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11
        gcc --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build wxUiEditor
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target wxUiEditor

    - name: Build Setup
      run: |
        cd build
        cpack -G DEB -C Release

    - name: Create Debian Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DebianSetup
        path: |
          build/wxUiEditor-*-Linux.deb
